package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"github.com/stripe/stripe-go/v74"
	"github.com/stripe/stripe-go/v74/checkout/session"
)

// GetCheckoutSession is the resolver for the getCheckoutSession field.
func (r *mutationResolver) GetCheckoutSession(ctx context.Context, paymentPlanID string) (string, error) {
	user, err := loggedInUser(ctx)
	if err != nil {
		return nil, internalError(err)
	}

	stripe.Key = "sk_test_51MbwHcJYDOv9WKcON9Olyvdvlvgk0C3conzPcEJsRRqitvp0aiZbfXxDulNkN26RfHUEa3uvbmyRBWuBe6F6lPQj00LeWQTo5K"

	params := &stripe.CheckoutSessionParams{
		LineItems: []*stripe.CheckoutSessionLineItemParams{
			{
				Price:    stripe.String("price_H5ggYwtDq4fbrJ"),
				Quantity: stripe.Int64(2),
			},
		},
		Mode:       stripe.String("payment"),
		SuccessURL: stripe.String("https://example.com/success"),
	}
	s, _ := session.New(params)

}
