package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/m-butterfield/prompter/server/app/data"
	"github.com/m-butterfield/prompter/server/app/graph/generated"
	"github.com/m-butterfield/prompter/server/app/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserCreds) (*data.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, credential string) (*data.User, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*data.User, error) {
	return nil, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, username string) (*data.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
